src/notepad/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from notes.views import note_list_view, finish_item, \
    recover_item, delete_item

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', note_list_view, name='note-list'),
    path('finish-item/<id>/', finish_item, name='finish-note-item'),
    path('recover-item/<id>/', recover_item, name='recover-note-item'),
    path('delete-item/<id>', delete_item, name='delete-note-item'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/notes/models.py
from django.db import models
from django.shortcuts import redirect, reverse
# Create your models here.
LABEL_CHOICES = (
    ('P', 'primary'),
    ('SE', 'secondary'),
    ('S', 'success'),
    ('D', 'danger'),
    ('W', 'warning'),
    ('I', 'info'),
    ('L', 'light'),
    ('D', 'dark')
)


class Note(models.Model):
    title = models.CharField(max_length=100)
    due_date = models.DateTimeField()
    labels = models.CharField(choices=LABEL_CHOICES, max_length=2)
    finished = models.BooleanField(default=False)

    def __str__(self):
        return self.title

src/notes/forms.py
from django import forms
from .models import Note

class NoteModelForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('title', 'due_date', 'labels')

src/notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Note
from .forms import NoteModelForm
# Create your views here.

def note_list_view(request):
    form = NoteModelForm()
    if request.method == "POST":
        form = NoteModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("note-list")
    to_do_list = Note.objects.filter(finished=False)
    finished_list = Note.objects.filter(finished=True)
    context = {'to_do_list': to_do_list,
               'finished_list': finished_list,
               "form": form}
    return render(request, "note_list.html", context)


def finish_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.finished = True
    note.save()
    return redirect('note-list')

def recover_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.finished = False
    note.save()
    return redirect('note-list')

def delete_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.delete()
    return redirect('note-list')

src/notes/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>Starter Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/starter-template/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://kit.fontawesome.com/3d28e052d4.js" crossorigin="anonymous"></script>
    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.5/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<main role="main" class="container">

{% block content %}
{% endblock content %}

</main><!-- /.container -->

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </body>
</html>

src/notes/templates/note_list.html
{% extends "base.html" %}
{% block content %}

<div class="text-center mt-5">
    <h2>To-Do list<a data-toggle="collapse" href="#collapseExample" role="button">
        <i class="fas fa-plus fa-sm" style="color:darkslategrey"></i></a></h2>
</div>
<hr />
<div class="collapse" id="collapseExample">
  <div class="card card-body">
      <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="id_title">Title</label>
        {{ form.title }}
      </div>
      <div class="form-group">
        <label for="id_due_date">Due date</label>
        {{ form.due_date }}
      </div>
      <div class="form-group form-check">
        <label for="id_label">Label</label>
        {{ form.labels }}
        <p><button type="submit" class="btn btn-primary">Create</button></p>
      </form>
      </div>
  </div>
</div>

<div class="row">
       {% for note in to_do_list %}
        <div class="col-12">
        {% include "note_snippet.html" with note_snippet_var=note type="DELETE" %}
        </div>
        {% endfor %}

</div>
<div class="text-center mt-5">
    <h2>Finished list</h2>
</div>
 <hr />
<div class="row">
       {% for note in finished_list %}
        <div class="col-12">
        {% include "note_snippet.html" with note_snippet_var=note type="ADD" %}
        </div>
        {% endfor %}
    </div>
</div>

 {% endblock %}

src/notes/templates/note_snippet.html
 <style>
h4 {
    position: relative;
}
.icons {
    position: absolute;
    right: 5px;
}
</style>
<div class="card">
    <div class="card-body">
            <h4>{{ note.title }}
                <span class="badge badge-{{ note.get_labels_display }}">
                {{ note.due_date }}
                </span>
                <span class="icons">
                {% if type == "DELETE" %}
                <a href="{% url 'finish-note-item' note_snippet_var.id %}"><i class="fas fa-check" style="color:darkslategrey"></i></a>
                {% else %}
                <a href="{% url 'recover-note-item' note_snippet_var.id %}"><i class="fas fa-times" style="color:darkslategrey"></i></a>
                {% endif %}
                 <a href="{% url 'delete-note-item' note_snippet_var.id %}"><i class="fas fa-trash" style="color:#ff0000"></i></a>
                </span>
            </h4>
    </div>
</div>